-- MySQL Script generated by MySQL Workbench
-- mar 10 mar 2020 22:03:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema despegarch
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `despegarch` ;

-- -----------------------------------------------------
-- Schema despegarch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `despegarch` ;
USE `despegarch` ;

-- -----------------------------------------------------
-- Table `despegarch`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`role` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`user` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(10) NOT NULL,
  `email` VARCHAR(70) NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `despegarch`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`login` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`login` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` TEXT(500) NOT NULL,
  `token` TEXT(500) NULL,
  `last_login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_login_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `despegarch`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`hotel` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`hotel` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` TEXT(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`flight` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`flight` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `from` VARCHAR(50) NOT NULL,
  `to` VARCHAR(45) NOT NULL,
  `airline` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`package` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`package` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` FLOAT NOT NULL,
  `hotel_id` BIGINT(20) UNSIGNED NOT NULL,
  `flight_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_package_hotel1_idx` (`hotel_id` ASC),
  INDEX `fk_package_flight1_idx` (`flight_id` ASC),
  CONSTRAINT `fk_package_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `despegarch`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_package_flight1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `despegarch`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despegarch`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `despegarch`.`sale` ;

CREATE TABLE IF NOT EXISTS `despegarch`.`sale` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  `passengers` INT NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `package_id` INT UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_package1_idx` (`package_id` ASC),
  INDEX `fk_sale_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_sale_package1`
    FOREIGN KEY (`package_id`)
    REFERENCES `despegarch`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `despegarch`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
